version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/var/log/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    container_name: kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - ./kibana/logs:/var/log/kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  timings:
    image: godaddy/timings:latest
    container_name: timings
    volumes:
      - ./timings/config/.config_sample.js:/src/.config.js
      - ./timings/logs:/src/logs
    ports:
      - "80:80"
    environment:
      NODE_ENV: "production"
      ES_HOST: "elasticsearch"
      KB_HOST: "${HOSTNAME}"
      DEBUG: "true"
    depends_on:
      - elasticsearch
      - kibana
    command: ['node', './server.js']
